import tkinter
window = tkinter.Tk()
window.title("Llogarit mesataren IE")
window.minsize(width=450,height=650)
window.config(bg="cyan")

Lendet = ["Hyrje në informatikë","Algoritmikë","Matematikë 1","C++","Hyrje në ekonomi","Anglisht 1","Strukturë të dhënash","Matematikë 2","Multimedia","Menaxhim","Marketing","Anglisht 2"]
lenda_1 = tkinter.Label(text = Lendet[0], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_1.grid(row=0,column=0)
lenda_1_input = tkinter.Entry()
lenda_1_input.focus()
lenda_1_input.grid(row=0,column=1)
lenda_2 = tkinter.Label(text = Lendet[1], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_2.grid(row=1,column=0)
lenda_2_input = tkinter.Entry()
lenda_2_input.grid(row=1,column=1)
lenda_3 = tkinter.Label(text = Lendet[2], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_3.grid(row=2,column=0)
lenda_3_input = tkinter.Entry()
lenda_3_input.grid(row=2,column=1)
lenda_4 = tkinter.Label(text = Lendet[3], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_4.grid(row=3,column=0)
lenda_4_input = tkinter.Entry()
lenda_4_input.grid(row=3,column=1)
lenda_5 = tkinter.Label(text = Lendet[4], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_5.grid(row=4,column=0)
lenda_5_input = tkinter.Entry()
lenda_5_input.grid(row=4,column=1)
lenda_6 = tkinter.Label(text = Lendet[5], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_6.grid(row=5,column=0)
lenda_6_input = tkinter.Entry()
lenda_6_input.grid(row=5,column=1)
lenda_7 = tkinter.Label(text = Lendet[6], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_7.grid(row=6,column=0)
lenda_7_input = tkinter.Entry()
lenda_7_input.grid(row=6,column=1)
lenda_8 = tkinter.Label(text = Lendet[7], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_8.grid(row=7,column=0)
lenda_8_input = tkinter.Entry()
lenda_8_input.grid(row=7,column=1)
lenda_9 = tkinter.Label(text = Lendet[8], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_9.grid(row=8,column=0)
lenda_9_input = tkinter.Entry()
lenda_9_input.grid(row=8,column=1)
lenda_10 = tkinter.Label(text = Lendet[9], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_10.grid(row=9,column=0)
lenda_10_input =  tkinter.Entry()
lenda_10_input.grid(row=9,column=1)
lenda_11 = tkinter.Label(text = Lendet[10], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_11.grid(row=10,column=0)
lenda_11_input = tkinter.Entry()
lenda_11_input.grid(row=10,column=1)
lenda_12 = tkinter.Label(text = Lendet[11], bg="cyan",padx=10,pady=10,fg="darkblue",font=("Arial",15,"normal"))
lenda_12.grid(row=11,column=0)
lenda_12_input = tkinter.Entry()
lenda_12_input.grid(row=11,column=1)
def calculator():
    return (int(lenda_1_input.get())*7+int(lenda_2_input.get())*6+int(lenda_3_input.get())*6+int(lenda_4_input.get())*5+int(lenda_5_input.get())*5+int(lenda_6_input.get())*3+int(lenda_7_input.get())*6+int(lenda_8_input.get())*5+int(lenda_9_input.get())*5+int(lenda_10_input.get())*4+int(lenda_11_input.get())*4+int(lenda_12_input.get())*3)/59
def result():
    new_window = tkinter.Toplevel(bg="cyan")
    new_window.minsize(width=400,height=300)
    new_window.title("Mesatarja")
    text = tkinter.Label(new_window,text=f"Mesatarja juaj është: {round(calculator(),2)}",bg="cyan",fg="Dark blue",font=("Times New Roman",15,"bold"))
    text.place(x=75,y=120)
calculate = tkinter.Button(text="Llogarit mesataren",fg="white",bg="darkblue",font=("Arial",15,"normal"),command=result)
calculate.grid(row=12,column=1)

window.mainloop()